config/routes.rb
Rails.application.routes.draw do
  scope "(:locale)", locale: /en|vi/ do
    root "static_pages#home"
    get "/help", to: "static_pages#help"
    get "/about", to: "static_pages#about"
    get "/contact", to: "static_pages#contact"
    get "/signup", to: "users#new"
    get "/login", to: "sessions#new"
    post "/login", to: "sessions#create"
    delete "/logout", to: "sessions#destroy"
    resources :users
    resources :account_activations, only: [:edit]
    resources :password_resets, only: [:new, :create, :edit, :update]
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home; end

  def help; end

  def about; end

  def contact; end
end

app/views/static_pages/about.html.erb
<% provide :title, t(".title") %>
<h1><%= t(".name")%></h1>
<p>
  <%= t(".the") %>
  <em><%= link_to t("ruby_on_rails_tutorial"), Settings.link.rails_tutorials %></em>
  <%= t(".path_of_the") %>
  <%= link_to t(".learn_enough"), Settings.link.learn_enough %>
  <%= t(".des1") %>
  <%= link_to t(".book"), Settings.link.tutorials_book %>
  <%= t(".and") %>
  <%= link_to t(".screencast"), Settings.link.rails_tutorials_screencast %>
  <%= t(".des2") %>
  <%= link_to t("ruby_on_rails"), Settings.link.rails %>.
  <%= t(".des3") %>
</p>

app/views/static_pages/contact.html.erb
<% provide :title, t(".title") %>
<h1><%= t(".name") %></h1>
<p>
  <%= t(".des") %>
  <%= link_to t(".contact_page"), Settings.link.rails_contact %>.
</p>

app/views/static_pages/help.html.erb
<% provide :title, t(".title") %>
<div class="center jumbotron">
  <h1><%= t(".name") %></h1>
  <p>
    <%= t(".des1") %>
    <%= link_to t(".help_page"), Settings.link.rails_help %>.
    <%= t(".des2") %>
    <em><%= link_to t("ruby_on_rails_tutorial"), Settings.link.rails_tutorials_book %></em>
    <%= t(".book") %>.
  </p>
</div>

app/views/static_pages/home.html.erb
<% provide :title, t(".title") %>
<div class="center jumbotron">
  <h1><%= t(".welcome") %></h1>
  <h2>
    <%= t(".description_1") %>
    <%= link_to t("ruby_on_rails_tutorial"), Settings.link.rails_tutorials %>
    <%= t(".description_2") %>
  </h2>
  <% if !logged_in? %>
    <%= link_to t(".sign_up_now"), signup_path, class: "btn btn-lg btn-primary" %>
  <% end %>
</div>

<%= link_to image_tag("rails.svg", class: "rails_logo", alt: "Rails logo"),
                        Settings.link.rails_tutorials %>